### ISSUE TITLE
Versioning our documentation

### ISSUE THREAD

**Issue by junpenglao** [blackjax-devs/blackjax#313]
Currently the doc is only showing HEAD, we should at least add latest release tag to the doc.

**Comment by rlouf** [comment]
Is there a Sphinx extension to do that?

**Comment by rlouf** [comment]
We should investigation actions [like this one](https://github.com/marketplace/actions/sphinx-build). One simple strategy is to build the doc in a new folder `tag_name` at each release, and overwrite the doc in the folder `head` on every push to `main`. The previous action also allows to bubble up Sphinx Build errors in the PR, which already goes a long way (since it tests running examples).

**Comment by junpenglao** [comment]
duplicate with #434
