### ISSUE TITLE
Unify SGMCMC API

### ISSUE THREAD

**Issue by SamDuffield** [blackjax-devs/blackjax#537]
Currently we have `sgld` and `sghmc` return `step` functions with no `init`, whilst `csgld` and `sgnht` return a `MCMCSamplingAlgorithm` with an `init` function.

It may be desirable to unify this API so that all SGMCMC algorithms have the same `MCMCSamplingAlgorithm` API with an `init` function that may just be a dummy function e.g. `lambda position: position`. This would be desirable so that the user can seamlessly switch between algorithms.

One question is how to format the `init`, i.e. should we enforce a `rng_key` input even though some algorithms (e.g. `csgld`) do not require a random key on `init`

To me, there seems to be four options

1. Leave it as is, each sampler has its own structure and we do not enforce an `init`
2. Enforce an `init` but no structured signature
3. Enforce an API like `init(rng_key: PRNGKey, position: PyTree, alpha: float = 0.01)` where `rng_key` is enforced but not necessarily used. Any additional arguments come after `position`.
4. Swap `position` and `rng_key` so that we can give the default `rng_key=None` for algorithms that do not need it.
E.g. `init(position: PyTree, rng_key: PRNGKey = None, alpha: float = 0.01)`. Problem here is if the algorithm `init` requires additional arguments that are not optional, they would have to come between `position` and `rng_key` which would disturb the _swappable_ API. This would not be a problem for the current `sgmcmc` suite but it could feasibly be for new algorithms.

We should also keep in mind the API for `blackjax.mcmc` and other parts of the package when deciding on this design.

WDYT @albcab ?

**Comment by junpenglao** [comment]
+1 to standardized it with `init` so the top layer API return a `MCMCSamplingAlgorithm` as well (option 4).

**Comment by albcab** [comment]
`MCMCSamplingAlgorithm` currently enforces an `init(position: PyTree)` signature and it should be kept this way. Exceptions like `ghmc` or `sgnht` should add `rng_key` after `position` as an additional argument and use `# type: ignore[arg-type]` to ignore the signature when testing. Any other additional argument can come before or after `rng_key`, but after `position`. 

In the specific case of `sghmc` and `sgnht` with the `alpha` and `beta` parameters: these are parameters of the kernel, so they should be passed in `__new__`. They are ignored now and passed as default, they should be passed as default in `__new__` (possibly after a `*,` because you'd hope that the end user that is modifying these parameters actually knows what they are doing). 

For `sgnht` you seem to be using `alpha` as an initial value for `xi`, you could keep it this way and avoid any additional parameters on the `init` function, or allow the user to pass any initial value for `xi`. If you choose the latter I would pass `init_xi` after `rng_key` with a default value of `None` and do something like `cls.init(rng_key, position, init_xi or alpha)`. 

In any case, going from `hmc`/`sghmc` to `ghmc`/`sgnht` will require the end user to pass an extra `rng_key` to the `init`. It should be this way because they are now working with a persistent momentum and you'd hope the end user is aware of this.

**Comment by albcab** [comment]
Maybe this ruins the seamlessly switching, but I do think it's important for the end user to know that there is another source of pseudo-randomness in the procedure now.
