### ISSUE TITLE
Removing high-level API classes

### ISSUE THREAD

**Issue by ciguaran** [blackjax-devs/blackjax#659]
This is a continuation of:

https://github.com/blackjax-devs/blackjax/issues/492

https://github.com/blackjax-devs/blackjax/pull/501

See two solution alternatives
https://github.com/blackjax-devs/blackjax/pull/657 replacing classes with objects of a single class 
https://github.com/blackjax-devs/blackjax/pull/658 replacing classes with functions

**Comment by reubenharry** [comment]
Thanks for looking into this! I tend to favour the more functional solution (#658)

**Comment by junpenglao** [comment]
Thank you for working on this!! This is a great suggest and i like the solutions!

So IIUC: #657 add the object to create high-level alias on top of the functional solution in #658.
While I also like #658 better, for backward compatibility we should go with #657. It should be easy to migrate/deprecate the object in the future because it is just one Python object and everything will be in the single file.

**Comment by albcab** [comment]
+1 what Junpeng said since #658 would break any script using blackjax
